CREATE TABLE USUARIOS (
    ID SERIAL PRIMARY KEY, 
    NOMBRE VARCHAR(30),
    USERNAME VARCHAR(30) UNIQUE,
    EMAIL VARCHAR(50) UNIQUE,
    FECHA_NACIMIENTO DATE,
    PASSWORD VARCHAR(30),
    ANIMAL VARCHAR(30)
);